from pathlib import Path

# -----Variables----

file_path = Path(__file__).with_name("input.txt") # Path to the input file, assumed to be in the same directory as the script
file_content = "" # Stores the content of the file as a string
list1 = [] # List to store elements at even indices
list2 = [] # List to store elements at odd indices


# -----Code Part 1-----

# Read the input file and split its contents into words/numbers
with file_path.open("r") as f:
  file_content = f.read().split()

# Separate file content into two lists: elements at even indices go to list1, and elements at odd indices go to list2
for i in range(len(file_content)):
  if i%2 == 0:
    list1.append(file_content[i])
  else:
    list2.append(file_content[i])

# Sort both lists (elements from even indices and odd indices, respectively)
list1_part1 = sorted(list1)
list2_part1 = sorted(list2)

# Calculate the solution for part 1
# For each pair of corresponding elements in the sorted lists, calculate the absolute difference and sum them up
solution_part1 = 0
for i in range(len(list1_part1)):
  dif = abs(int(list1_part1[i])-int(list2_part1[i]))
  solution_part1 += dif

# Print the solution for part 1
print(solution_part1)


# -----Code Part 2-----

# Prepare lists for part 2
list1_part2 = list1 # Use the original unsorted list1
list2_part2 = list2 # Use the original unsorted list2

# Calculate the solution for part 2
# For each element in list1, calculate its product with the count of its occurrences in list2
solution_part2 = 0
for item in list1_part2:
  score = int(item) * list2_part2.count(item) # Multiply the integer value of the item by its count in list2
  solution_part2 += score # Add the score to the solution

# Print the solution for part 2
print(solution_part2)


# -----AI Disclaimer-----

# This code for this challenge was written without the help of AI. The comments, which have been added for documentation purposes, were generated by ChatGPT.