from pathlib import Path 

file_path = Path(__file__).with_name("input.txt")
with file_path.open("r") as f:
    file_content = f.read()

# -----General----
    
# -----Code Part 1-----

# -----Code Part 2-----

# -----Documentation-----
# This code for this challenge was written without the help of AI. The documentation was generated by ChatGPT.